sudo: required
language: go
go:
  - 1.9

notifications:
  email: false

services:
  - docker

env:
  - DEP_VERSION="0.4.1"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - make download-tools

install:
  - dep ensure -v

script:
  - make test
  - make check

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - if [[ $TRAVIS_TAG != "v"* ]]; then exit 1; fi
  - VERSION=$(echo $TRAVIS_TAG | cut -c 2-) make build-all

deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: build/*.zip
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: bash docker-push.sh
    skip_cleanup: true
    on:
        tags: true